kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: administrateur
subjects:
  kind: ServiceAccount
  name: Administrateur
