kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cli-bind
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: client
subjects:
  kind: ServiceAccount
  name: Client
