kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev
  namespace: wordpress
rules:
- apiGroups: ""
  resources: "pods", "pods/log"
  verbs: "list", "get", "watch"
- apiGroups: ""
  resources: "wordpress"
  verbs: "list","get","watch","delete","update"
