kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysop-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sysops
subjects:
  kind: ServiceAccount
  name: SysOp
