kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysops
rules:
  apiGroups: ""
  resources: "pods", "pods/log", "kubedb", "wordpress"
  verbs: "list","get","watch","delete","update"
