apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-mysql
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"